### ISSUE TITLE
react-dom module dependency error

### ISSUE THREAD

**Issue by ArcstreamAV** [JedWatson/react-hammerjs#23]
We have the following error after installing react-hammerjs (via npm):

```sh
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'react-dom' from '/root/project/as-intuit-table/node_modules/react-hammerjs/src'
    at /root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /root/project/as-intuit-table/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

Installing react-dom (0.14.0) fixes it.. but should it be in your deps?

**Comment by nightlyop** [comment]
I've the same problem. Please fix it. Thanks!
